[theme]
base = "dark"
primaryColor = "#00B8D4"
backgroundColor = "#0b1e2d"
secondaryBackgroundColor = "#0f2a3a"
textColor = "#e6f2ff"
font = "sans serif"

[server]
maxUploadSize = 5000
maxMessageSize = 5000

[browser]
gatherUsageStats = false


